Update ros2_ci.yml

diff --git a/.github/workflows/ros2_ci.yml b/.github/workflows/ros2_ci.yml
--- a/.github/workflows/ros2_ci.yml
+++ b/.github/workflows/ros2_ci.yml
@@ -12,7 +12,7 @@ on:
     types: [published]
 
 jobs:
-  ci:
+  build_and_test:
     strategy:
       matrix:
         rosdistro: [ humble ]
@@ -21,11 +21,11 @@ jobs:
 
     continue-on-error: true
 
-    # container:
-    #   # There don't seem to be ROS perception docker images for ros2 yet, so we
-    #   # use the base imageand install the rest of the dependencies using rosdep
-    #   # each time.
-    #   image: ros:${{ matrix.rosdistro }}-ros-base
+    container:
+      # There don't seem to be ROS perception docker images for ros2 yet, so we
+      # use the base imageand install the rest of the dependencies using rosdep
+      # each time.
+      image: ros:${{ matrix.rosdistro }}-ros-base
 
     steps:
     - uses: actions/checkout@v2
@@ -38,52 +38,36 @@ jobs:
     - name: Install diagnostic-updater
       run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
 
-  build:
-    strategy:
-      matrix:
-        rosdistro: [ humble ]
-
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        path: src/ros2_topic_sample
-
     - name: Build tests
       id: build_test
       run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon build --event-handlers console_cohesion+
-      # continue-on-error: true
+      continue-on-error: true
 
-    # - name: build_test command success
-    #   if: steps.build_test.outcome == 'success'
-    #   run: echo "result - success"
+    - name: build_test command success
+      if: steps.build_test.outcome == 'success'
+      run: echo "result - success"
 
-    # - name: build_test command failure
-    #   if: steps.build_test.outcome == 'failure'
-    #   run: echo "result - failure" && exit 1
-
-  run_test:
-    strategy:
-      matrix:
-        rosdistro: [ humble ]
-
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        path: src/ros2_topic_sample
+    - name: build_test command failure
+      if: steps.build_test.outcome == 'failure'
+      run: echo "result - failure" && exit 1
 
     - name: Run tests
       id: run_test
       run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon test --event-handlers console_cohesion+ && colcon test-result
-      # continue-on-error: true
+      continue-on-error: true
 
-    # - name: run_test command success
-    #   if: steps.run_test.outcome == 'success'
-    #   run: echo "result - success"
+    - name: run_test command success
+      if: steps.run_test.outcome == 'success'
+      run: echo "result - success"
 
-    # - name: run_test command failure
-    #   if: steps.run_test.outcome == 'failure'
-    #   run: echo "result - failure" && exit 1
+    - name: run_test command failure
+      if: steps.run_test.outcome == 'failure'
+      run: echo "result - failure" && exit 1
+
+  check_status:
+    needs: build_and_test
+    if: ${{ needs.build_and_test.result != 'success' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set Workflow Status to Failure
+        run: exit 1
