Update ros2_ci.yml

diff --git a/.github/workflows/ros2_ci.yml b/.github/workflows/ros2_ci.yml
--- a/.github/workflows/ros2_ci.yml
+++ b/.github/workflows/ros2_ci.yml
@@ -1,4 +1,4 @@
-name: Build and run ROS2 tests
+name: build and test
 
 on:
   push:
@@ -15,7 +15,10 @@ jobs:
   build_and_test:
     strategy:
       matrix:
-        rosdistro: [ humble ]
+        os:
+          - ubuntu-22.04
+        rosdistro:
+          - humble
 
     runs-on: ubuntu-latest
 
@@ -23,38 +26,47 @@ jobs:
       image: ros:${{ matrix.rosdistro }}-ros-base
 
     steps:
-    - uses: actions/checkout@v2
-      with:
-        path: src/ros2_topic_sample
+      - name: Setup directories
+        run: mkdir -p ros2_ws/src
+        
+      - name: Check out repository
+        uses: actions/checkout@v3
+        with:
+          path: ros2_ws/src/ros2_topic_sample
 
-    - name: Install dependencies
-      run: rosdep update --include-eol-distros && apt-get update && rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}
+#       - name: Install dependencies
+#         run: rosdep update --include-eol-distros && apt-get update && rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}
 
-    - name: Install diagnostic-updater
-      run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
+      - name: Install diagnostic-updater
+        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
 
-    - name: Build tests
-      id: build_test
-      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon build --event-handlers console_cohesion+
-      continue-on-error: true
+      - name: Build tests
+        id: build_test
+        run: |
+          source /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
+          colcon build
+        continue-on-error: true
 
-    - name: build_test command success
-      if: steps.build_test.outcome == 'success'
-      run: echo "result - success"
+      - name: build_test command success
+        if: steps.build_test.outcome == 'success'
+        run: echo "result - success"
 
-    - name: build_test command failure
-      if: steps.build_test.outcome == 'failure'
-      run: echo "result - failure" && exit 1
+      - name: build_test command failure
+        if: steps.build_test.outcome == 'failure'
+        run: echo "result - failure" && exit 1
 
-    - name: Run tests
-      id: run_test
-      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon test --event-handlers console_cohesion+ && colcon test-result
-      continue-on-error: true
+      - name: Run tests
+        id: run_test
+        run: |
+          source /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+          colcon test && 
+          colcon test-result
+        continue-on-error: true
 
-    - name: run_test command success
-      if: steps.run_test.outcome == 'success'
-      run: echo "result - success"
+      - name: run_test command success
+        if: steps.run_test.outcome == 'success'
+        run: echo "result - success"
 
-    - name: run_test command failure
-      if: steps.run_test.outcome == 'failure'
-      run: echo "result - failure" && exit 1
+      - name: run_test command failure
+        if: steps.run_test.outcome == 'failure'
+        run: echo "result - failure" && exit 1
